# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chenyansu\Documents\GitHub\pyqt\mw.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(891, 730)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(30, 100, 91, 21))
        self.label.setObjectName("label")
        self.base_url_lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.base_url_lineEdit.setGeometry(QtCore.QRect(90, 520, 311, 21))
        self.base_url_lineEdit.setObjectName("base_url_lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 530, 54, 12))
        self.label_2.setObjectName("label_2")
        self.postfix_lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.postfix_lineEdit.setGeometry(QtCore.QRect(270, 620, 61, 20))
        self.postfix_lineEdit.setObjectName("postfix_lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(240, 630, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(30, 630, 41, 16))
        self.label_5.setObjectName("label_5")
        self.amount_lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.amount_lineEdit.setGeometry(QtCore.QRect(70, 620, 41, 20))
        self.amount_lineEdit.setObjectName("amount_lineEdit")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(120, 630, 54, 12))
        self.label_6.setObjectName("label_6")
        self.finish_num_lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.finish_num_lineEdit.setGeometry(QtCore.QRect(180, 620, 41, 20))
        self.finish_num_lineEdit.setObjectName("finish_num_lineEdit")
        self.name_lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.name_lineEdit.setGeometry(QtCore.QRect(90, 570, 311, 20))
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(30, 580, 41, 16))
        self.label_7.setObjectName("label_7")
        self.add_task_pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.add_task_pushButton.setGeometry(QtCore.QRect(340, 640, 75, 23))
        self.add_task_pushButton.setObjectName("add_task_pushButton")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(370, 10, 111, 20))
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(420, 60, 20, 271))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.display_textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.display_textBrowser.setGeometry(QtCore.QRect(460, 80, 411, 551))
        self.display_textBrowser.setObjectName("display_textBrowser")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(600, 60, 101, 16))
        self.label_9.setObjectName("label_9")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(420, 370, 21, 341))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.clear_display_pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.clear_display_pushButton.setGeometry(QtCore.QRect(790, 640, 75, 23))
        self.clear_display_pushButton.setObjectName("clear_display_pushButton")
        self.label_19 = QtWidgets.QLabel(self.centralWidget)
        self.label_19.setGeometry(QtCore.QRect(20, 710, 181, 16))
        self.label_19.setObjectName("label_19")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(30, 200, 61, 16))
        self.label_11.setObjectName("label_11")
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(100, 200, 311, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.quick_insert_lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.quick_insert_lineEdit.setGeometry(QtCore.QRect(30, 230, 391, 20))
        self.quick_insert_lineEdit.setText("")
        self.quick_insert_lineEdit.setObjectName("quick_insert_lineEdit")
        self.quick_insert_pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.quick_insert_pushButton.setGeometry(QtCore.QRect(340, 260, 75, 23))
        self.quick_insert_pushButton.setObjectName("quick_insert_pushButton")
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setGeometry(QtCore.QRect(20, 180, 81, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setGeometry(QtCore.QRect(90, 190, 20, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.url_lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.url_lineEdit.setGeometry(QtCore.QRect(30, 130, 301, 20))
        self.url_lineEdit.setText("")
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.analyse_url_pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.analyse_url_pushButton.setGeometry(QtCore.QRect(340, 130, 75, 23))
        self.analyse_url_pushButton.setObjectName("analyse_url_pushButton")
        self.line_7 = QtWidgets.QFrame(self.centralWidget)
        self.line_7.setGeometry(QtCore.QRect(90, 90, 20, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralWidget)
        self.line_8.setGeometry(QtCore.QRect(100, 100, 311, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralWidget)
        self.line_9.setGeometry(QtCore.QRect(20, 80, 81, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralWidget)
        self.line_10.setGeometry(QtCore.QRect(100, 310, 20, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralWidget)
        self.line_11.setGeometry(QtCore.QRect(110, 319, 311, 21))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(40, 320, 61, 16))
        self.label_12.setObjectName("label_12")
        self.line_12 = QtWidgets.QFrame(self.centralWidget)
        self.line_12.setGeometry(QtCore.QRect(30, 300, 81, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.history_comboBox = QtWidgets.QComboBox(self.centralWidget)
        self.history_comboBox.setGeometry(QtCore.QRect(40, 370, 361, 22))
        self.history_comboBox.setObjectName("history_comboBox")
        self.delete_a_history_pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.delete_a_history_pushButton.setGeometry(QtCore.QRect(40, 410, 75, 23))
        self.delete_a_history_pushButton.setObjectName("delete_a_history_pushButton")
        self.add_history_pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.add_history_pushButton.setGeometry(QtCore.QRect(130, 410, 75, 23))
        self.add_history_pushButton.setObjectName("add_history_pushButton")
        self.clean_history_pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.clean_history_pushButton.setGeometry(QtCore.QRect(330, 410, 75, 23))
        self.clean_history_pushButton.setObjectName("clean_history_pushButton")
        self.warning_label = QtWidgets.QLabel(self.centralWidget)
        self.warning_label.setGeometry(QtCore.QRect(120, 660, 111, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.warning_label.setFont(font)
        self.warning_label.setText("")
        self.warning_label.setObjectName("warning_label")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "便捷工具1"))
        self.label_2.setText(_translate("MainWindow", "base_url"))
        self.postfix_lineEdit.setText(_translate("MainWindow", ".ts"))
        self.label_4.setText(_translate("MainWindow", "后缀"))
        self.label_5.setText(_translate("MainWindow", "总数量"))
        self.amount_lineEdit.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "完成数量"))
        self.finish_num_lineEdit.setText(_translate("MainWindow", "-1"))
        self.label_7.setText(_translate("MainWindow", "影片名"))
        self.add_task_pushButton.setText(_translate("MainWindow", "添加任务"))
        self.label_8.setText(_translate("MainWindow", "小王霸流媒体下载器"))
        self.label_9.setText(_translate("MainWindow", "历史任务显示窗口"))
        self.clear_display_pushButton.setText(_translate("MainWindow", "清屏"))
        self.label_19.setText(_translate("MainWindow", "https://github.com/chenyansu"))
        self.label_11.setText(_translate("MainWindow", "便捷工具2"))
        self.quick_insert_pushButton.setText(_translate("MainWindow", "快速导入"))
        self.analyse_url_pushButton.setText(_translate("MainWindow", "url拆解"))
        self.label_12.setText(_translate("MainWindow", "便捷工具3"))
        self.delete_a_history_pushButton.setText(_translate("MainWindow", "删除该记录"))
        self.add_history_pushButton.setText(_translate("MainWindow", "导入记录"))
        self.clean_history_pushButton.setText(_translate("MainWindow", "清空记录"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
